camera0: 0
camera1: 2
frame_width: 320
frame_height: 320
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1
checkerboard_box_size_scale : 1.5
checkerboard_rows: 7
checkerboard_columns: 10
cooldown: 100
